export const authCopy = {
  email: "邮箱",
  emailPlaceholder: "输入您的邮箱",
  sending: "发送中...",
  registrationDisabledDesc: "只有账户的登录邮箱可以登录。",
  productTagline: "一个安静的个人账本",
  emailLoginTitle: "邮箱登录",
  emailLoginDesc: "我们会发送一个简短的验证码。",
  reauthRequiredNotice: "请重新登录以继续此操作。",
  credentialsChangedNotice: "登录凭据已更新，请重新登录。",
  noAccountTitle: "还没有账户",
  noAccountDesc: "在服务器上依次运行以下命令，再打开输出的链接添加通行密钥。",
  verifyCode: "验证验证码",
  verifyCodeDesc: (v: { email: string | number }) => `输入发送至 ${v.email} 的 6 位验证码`,
  sendVerificationCode: "发送验证码",
  enterCode: "输入验证码",
  verifying: "验证中...",
  verify: "验证",
  changeEmail: "修改邮箱",
  resend: "重新发送",
  resendIn: (v: { seconds: string | number }) => `${v.seconds} 秒后可重发`,
  codeExpiresTimer: (v: { time: string | number }) => `验证码有效期 ${v.time}`,
  codeExpired: "验证码已过期",
  error: "登录出错",
  errorDesc: "登录过程中发生错误，请重试。",
  rateLimitedDesc: "尝试次数过多，请稍后再试。",
  rateLimitedWait: (v: { minutes: number }) => `尝试次数过多，请 ${v.minutes} 分钟后再试。`,
  rateLimitUnavailableDesc: "登录保护服务暂时不可用，请稍后重试。",
  otpLockedDesc: "验证码尝试次数过多，请稍后再试。",
  sendCodeFailed: "发送验证码失败",
  invalidEmailFormat: "邮箱格式不正确",
  emailAuthNotConfigured: "邮箱登录未配置，请联系管理员",
  emailSendFailed: "邮件发送失败，请稍后重试",
  unexpectedError: "发生意外错误",
  invalidCode: "请输入有效的 6 位验证码",
  verifyFailed: "验证码无效",
  resendFailed: "重新发送验证码失败",
  resendInProgress: "正在发送新的验证码…",
  verifyExpired: "验证码已过期，请重新获取。",
  codeExpiredMessage: "验证码已过期，请重新获取。",
  errorConfigurationDesc: "服务器配置存在问题，请联系管理员。",
  devSignIn: "以开发身份进入",
  devSignInDesc: "仅限本地开发，免验证码直接进入。",
  devSignInFailed: "开发会话启动失败",
  otpDigitLabel: (v: { index: string | number; length: string | number }) =>
    `第 ${v.index} 位，共 ${v.length} 位`,
  passkeySignIn: "使用通行密钥登录",
  passkeyFailed: "通行密钥登录失败，请重试或改用邮箱验证码。",
  orDivider: "或",
};

export const enrollCopy = {
  title: "添加通行密钥",
  description: "用本机的指纹、面容或密码创建通行密钥，链接仅可用一次。",
  submit: "创建通行密钥",
  passkeyName: "我的设备",
  unsupported: "当前浏览器不支持通行密钥，请换一个浏览器打开这个链接。",
  failed: "未能创建通行密钥，请重试。",
  duplicate: "这台设备已保存过这个账户的通行密钥。",
  expired: "操作超时，请重试。",
  rateLimited: "尝试次数过多，请稍后再试。",
  rateLimitUnavailable: "登录保护服务暂时不可用，请稍后重试。",
  unexpected: "发生意外错误",
  invalidLinkTitle: "链接不可用",
  invalidLinkDesc: "链接已失效，请在服务器上重新运行 npm run account:enroll。",
  backToLogin: "返回登录",
};
