import type { CommonLucideIcon } from "@/config/icons";

export const settingsCopy = {
  account: "账户",
  appearance: "外观",
  bookkeepingRules: "记账规则",
  theme: "主题",
  themeAuto: "跟随系统",
  themeLight: "浅色模式",
  themeDark: "深色模式",
  aiLanguage: "AI 输出语言",
  mainCurrency: "主货币",
  collapseEntries: "默认折叠记录",
  preferredCurrencies: "偏好货币",
  preferredCurrenciesNone: "未选择币种",
  preferredCurrenciesSummary: (v: { currencies: string | number; count: string | number }) =>
    `${v.currencies}（${v.count} 种）`,
  preferredCurrenciesSearch: "搜索币种",
  preferredCurrenciesNoResults: "没有匹配的币种",
  categories: "分类",
  manageCategories: "管理分类",
  switchPreset: "切换预设",
  presetDialogTitle: "切换分类预设",
  presetOptionDefault: "默认",
  presetOptionConcise: "简洁",
  presetOptionDefaultDesc: "13 个分类，覆盖较细，适合想把每笔支出都分清楚的人。",
  presetOptionConciseDesc: "更粗的 6 类，适合只想看大方向的人。",
  presetMappingTitle: "旧分类的去向",
  presetMappingUnset: "请选择",
  presetMappingKeep: "保留，不迁移",
  presetSummary: (v: { count: string | number; entries: string | number }) =>
    `${v.count} 个分类直接迁移，涉及 ${v.entries} 条明细`,
  presetSummaryUnset: (v: { count: string | number }) => `${v.count} 个分类暂未指定`,
  presetSummaryNone: "请至少指定一个分类迁移",
  presetApply: "确认切换",
  presetConfirmTitle: (v: { preset: string | number }) => `切换到「${v.preset}」？`,
  presetConfirmDescription: (v: {
    entries: string | number;
    merged: string | number;
    created: string | number;
    retained: string | number;
  }) =>
    `将迁移 ${v.entries} 条明细，合并 ${v.merged} 个旧分类，新增 ${v.created} 个分类，并保留 ${v.retained} 个额外分类。`,
  presetApplyFailed: "未切换分类预设，请重试。",
  presetWholeCategoryDescription: "本次按旧分类整体迁移，不会用 AI 逐条重新判断。",
  presetUncategorizedDescription: "未分类的明细不会自动归类。",
  presetAfterDescription: "切换后可前往明细，选择需要 AI 重新分类的记录。",
  presetMergeIrreversible: "合并后无法通过切回原预设自动恢复原有归属。",
  presetDraftChanged: "分类集合已在后台变化。请重新加载分类后再提交。",
  presetReloadCategories: "重新加载分类",
  presetSuggested: "建议",
  presetExpandDescription: "展开描述",
  presetNoChanges: "已是此分类结构",
  presetApplying: "正在切换…",
  presetFinalStructure: "应用后的结果",
  presetGoToDetails: "去明细重新分类",
  categoryAssignmentActive: "分类任务正在进行。完成或停止任务后，可以切换预设或修改候选分类。",
  categoryAssignmentViewTask: "查看任务",
  presetImpactPreview: (v: {
    entries: string | number;
    merged: string | number;
    created: string | number;
    retained: string | number;
  }) =>
    `当前预估：迁移 ${v.entries} 条明细，合并 ${v.merged} 个旧分类，新增 ${v.created} 个分类，保留 ${v.retained} 个额外分类。`,
  presetResultSummary: (v: {
    entries: string | number;
    created: string | number;
    removed: string | number;
    retained: string | number;
  }) =>
    `实际迁移 ${v.entries} 条明细，新增 ${v.created} 个分类，移除 ${v.removed} 个旧分类，保留 ${v.retained} 个额外分类。`,
  moveCategoryUp: (v: { name: string | number }) => `上移分类 ${v.name}`,
  moveCategoryDown: (v: { name: string | number }) => `下移分类 ${v.name}`,
  editCategory: (v: { name: string | number }) => `编辑分类 ${v.name}`,
  deleteCategory: (v: { name: string | number }) => `删除分类 ${v.name}`,
  editCategoryDialog: "编辑分类",
  deleteCategoryDialog: "删除分类",
  deleteCategoryDescription: (v: { name: string | number }) =>
    `确定删除分类“${v.name}”吗？相关明细将变为未分类。`,
  categoryName: "分类名称",
  aiPrompt: "账本提示词",
  newCategoryPlaceholder: "新分类名称",
  addCategory: "添加",
  updateSuccess: "设置更新成功",
  updateFailed: "更新失败，请稍后重试",
  unsupportedCurrency: "所选币种暂不受汇率数据支持",
  validationFailed: "设置内容无效，请检查后重试",
  updateConflict: "未保存：设置已在别处更改，已载入最新设置，请重新修改。",
  saving: "(保存中...)",
  mainCurrencyMustBeEnabled: "主货币必须包含在偏好货币中。",
  categoriesSaved: "分类已保存",
  saveCategoriesFailed: "未保存任何分类更改，请修正后重试。",
  discardCategoryChangesTitle: "放弃分类更改？",
  discardCategoryChangesDescription: "尚未保存的分类新增、编辑、删除和排序都会丢失。",
  discardCategoryEditTitle: "放弃分类编辑？",
  discardCategoryEditDescription: "此分类编辑器中的更改将丢失。",
  credentialCreated: "密钥已创建",
  credentialDeleted: "密钥已删除",
  createFailed: "创建失败",
  deleteFailed: "删除失败",
  categoryDescription: "分类描述",
  generatingMetadata: "正在生成描述和图标...",
  retryMetadata: "重试生成",
  categoryItemCount: (v: { count: string | number }) => `${v.count} 条明细`,
  uncategorized: "未分类",
  signOut: "退出登录",
  signOutConfirmTitle: "退出登录？",
  signOutConfirmDescription: "结束当前会话前，将清理本机缓存的账本数据。",
  selectIcon: "选择图标",
  selectedIcon: (v: { name: string | number }) => `已选择图标：${v.name}`,
  icons: "图标",
  iconNames: {
    Utensils: "餐饮",
    Coffee: "咖啡",
    Wine: "酒水",
    ShoppingBag: "购物袋",
    ShoppingCart: "购物车",
    Shirt: "服装",
    Gamepad2: "游戏",
    Music: "音乐",
    Ticket: "门票",
    Film: "电影",
    Bus: "公交",
    Car: "汽车",
    TrainFront: "火车",
    Plane: "飞机",
    Bike: "自行车",
    Stethoscope: "医疗",
    Heart: "健康",
    House: "住房",
    Building: "建筑",
    Key: "钥匙",
    Book: "书籍",
    GraduationCap: "教育",
    Laptop: "电脑",
    Phone: "手机",
    Camera: "相机",
    Headphones: "耳机",
    Wifi: "网络",
    Wallet: "钱包",
    CreditCard: "信用卡",
    Banknote: "现金",
    Receipt: "小票",
    PiggyBank: "储蓄",
    Briefcase: "工作",
    Hammer: "维修",
    Dumbbell: "健身",
    Baby: "婴幼儿",
    Dog: "宠物",
    Gift: "礼物",
    Glasses: "眼镜",
    Umbrella: "雨具",
    Watch: "手表",
    Hotel: "酒店",
    MapPin: "地点",
    Luggage: "行李",
    Crown: "皇冠",
    Star: "星标",
    Lightbulb: "创意",
    Palette: "艺术",
    Scissors: "理发",
    Tag: "标签",
    Truck: "配送",
    Zap: "水电",
    Package: "其他",
  } satisfies Record<CommonLucideIcon, string>,
  credentialBookChanged: "已更新密钥分账",
  credentialBookChangeFailed: "修改密钥分账失败",
  categoriesChangedElsewhere: "分类已在别处更改，这些修改无法保存。",
  reloadCategories: "载入最新分类",
};

export const settingsAccountCopy = {
  passkeySection: "通行密钥",
};

export const settingsBooksCopy = {
  title: "分账",
  description: "每笔记录属于一个分账；总账始终汇总全部分账，无需设置。",
  name: "名称",
  namePlaceholder: "分账名称",
  add: "新增分账",
  addTitle: "新增分账",
  addDesc: "起一个简短的名字，之后可以重命名或归档。",
  rename: (v: { name: string | number }) => `重命名 ${v.name}`,
  timeZone: "时区",
  timeZoneAuto: "自动",
  timeZoneAutoDetected: (v: { timeZone: string | number }) => `自动（${v.timeZone}）`,
  moveUp: (v: { name: string | number }) => `上移 ${v.name}`,
  moveDown: (v: { name: string | number }) => `下移 ${v.name}`,
  archive: "归档",
  archiveTitle: (v: { name: string | number }) => `归档「${v.name}」？`,
  archiveDesc:
    "归档后这个分账不再出现在切换器和选择器中；它的记录仍计入总账，可以随时从设置中恢复。",
  archived: "分账已归档",
  restore: "恢复",
  restored: "分账已恢复",
  archivedBadge: "已归档",
  archivedSection: "已归档的分账",
  delete: "删除",
  deleteTitle: (v: { name: string | number }) => `删除「${v.name}」？`,
  deleteDesc: "删除后无法恢复。只有没有任何记录（包括已删除的记录）且没有 API 密钥的分账可以删除。",
  deleted: "分账已删除",
  hasRecords: "该分账还有记录，不能删除。请改为归档。",
  hasCredentials: "还有 API 密钥绑定到该分账，请先改绑这些密钥。",
  invalidName: "分账名称需要 1–20 个字符。",
  notFound: "找不到该分账，可能已被删除。",
  lastBook: "最后一个分账不能归档或删除。",
  nameTaken: "已有同名分账。",
  saveFailed: "保存分账失败。",
  empty: "还没有分账。",
};

export const settingsPasskeysCopy = {
  description: "用指纹、面容或设备密码登录，不需要输入邮箱。",
  unsupported: "当前浏览器不支持通行密钥。",
  add: "添加通行密钥",
  addTitle: "添加通行密钥",
  addDesc: "给它起个名字，方便以后辨认是哪台设备。接下来浏览器会请你确认。",
  defaultName: "我的设备",
  name: "名称",
  create: "继续",
  empty: "还没有通行密钥，目前只能用邮箱验证码登录。",
  createdAt: (v: { date: string | number }) => `添加于 ${v.date}`,
  lastUsedAt: (v: { date: string | number }) => `上次使用 ${v.date}`,
  rename: (v: { name: string | number }) => `重命名 ${v.name}`,
  renameTitle: "重命名通行密钥",
  renameDesc: "名称只用于在这里辨认，不影响登录。",
  delete: (v: { name: string | number }) => `删除 ${v.name}`,
  deleteTitle: (v: { name: string | number }) => `删除 ${v.name}？`,
  deleteDesc: "这台设备将不能再用通行密钥登录。",
  deleteLastDesc: "这是最后一个通行密钥。删除后只能用邮箱验证码登录。",
  added: "已添加通行密钥",
  renamed: "已重命名",
  deleted: "已删除通行密钥",
  expired: "操作超时，请重试。",
  invalid: "浏览器返回的通行密钥无法验证，请重试。",
  duplicate: "这台设备已经添加过通行密钥。",
  notFound: "找不到这个通行密钥，请刷新后重试。",
  reauthRequired: "请重新登录后再继续此操作。",
  unknown: "出了点问题，请重试。",
};

export const settingsEmailsCopy = {
  title: "登录邮箱",
  add: "添加邮箱",
  addTitle: "添加登录邮箱",
  addDesc: "我们会向新邮箱发送验证码，确认后它才能用于登录。",
  newEmail: "新邮箱地址",
  sendCode: "发送验证码",
  verificationCode: "6 位验证码",
  verify: "确认",
  remove: (v: { email: string | number }) => `移除 ${v.email}`,
  removeTitle: (v: { email: string | number }) => `移除 ${v.email}？`,
  removeDesc: "该邮箱将无法再登录。账户至少要保留一个邮箱。",
  lastEmail: "账户至少要保留一个登录邮箱。",
  codeSent: "验证码已发送",
  added: "已添加邮箱",
  sessionsEnded: "邮箱已移除，所有设备均已退出登录。",
  invalidEmail: "请输入有效的邮箱地址。",
  invalidCode: "验证码不正确。",
  expiredCode: "验证码已过期，请重新获取。",
  emailInUse: "该邮箱已被使用。",
  rateLimited: "请稍后再获取验证码。",
  locked: "尝试次数过多，验证已暂时锁定。",
  reauthRequired: "请重新登录后再继续此操作。",
  unknown: "出了点问题，请重试。",
};

export const serviceCredentialsCopy = {
  title: "API 密钥",
  newCredential: "新建密钥",
  noCredentials: "暂无服务密钥",
  createdAt: (v: { date: string | number }) => `创建于 ${v.date}`,
  createTitle: "新建服务密钥",
  createDesc: "创建一个新的服务密钥用于外部系统访问此账本。",
  namePlaceholder: "密钥名称 (例如: 自动记账脚本)",
  createSuccessTitle: "服务密钥创建成功",
  createSuccessDesc: "这是您唯一一次查看完整密钥的机会。请立即复制并妥善保存。",
  copy: "复制",
  copyCredential: "复制密钥",
  saved: "我已保存",
  deleteTitle: "删除服务密钥",
  deleteDesc: (v: { name: string | number }) =>
    `确定要删除凭证“${v.name}”吗？删除后使用此凭证的外部应用将无法访问。此操作无法撤销。`,
  deleteButton: (v: { name: string | number }) => `删除${v.name}`,
  maxActive: "每个账本最多可有 20 个有效服务凭据。",
  bookUnavailable: "所选分账不可用：它可能已被归档或删除。请选择其他分账。",
  copied: "密钥已复制到剪贴板",
  bookDesc: "通过此密钥上传的记录会归入该分账。",
  changeBook: (v: { name: string | number }) => `修改「${v.name}」的分账`,
  archivedBook: "（已归档）",
};
