export const sourceDocumentCardCopy = {
  expand: "展开",
  collapse: "折叠",
  moreActions: "更多操作",
  image: "图片",
  imageAlt: (v: { index: string | number }) => `图片 ${v.index}`,
  untitled: "未命名账单",
  processing: "处理中",
  completed: "已完成",
  cancelled: "已取消",
};

export const sourceDocumentInputCopy = {
  placeholder: "输入消费记录，例如：午饭 35 元… (支持粘贴图片)",
  image: "图片",
  send: "发送",
  uploadSuccess: "提交成功",
  retrySuccess: "已开始重新处理",
  retryError: "重新处理失败",
  entryDate: "日期（可选）",
  preparing: "正在准备图片",
  uploading: "正在上传图片",
  finalizing: "正在确认上传",
  submitting: "正在创建账单，此阶段无法取消",
  cancelling: "正在取消上传…",
  imageTooLarge: (v: { fileName: string | number }) =>
    `图片过大：${v.fileName}。请使用更小的图片。`,
  imageUnsupported: (v: { fileName: string | number }) =>
    `不支持的图片格式：${v.fileName}。请使用 JPEG、PNG、GIF 或 WebP。`,
  imageReadError: "无法读取所选图片，请重新选择。",
  imageUploadError: "图片上传失败，输入内容已保留，请重试。",
  networkError: "网络请求已中断，输入内容已保留，请重试。",
  validationError: "账单内容校验失败，请检查后重试。",
  createError: "创建账单失败，输入内容已保留，请重试。",
  tooManyImages: (v: { count: string | number }) => `最多只能上传 ${v.count} 张图片。`,
  cancelUpload: "取消上传",
  savedMayBeHidden: "已保存，但当前筛选可能隐藏这张账单。",
  savedToOtherBook: (v: { book: string | number }) =>
    `已保存到「${v.book}」，当前视图不会显示这张账单。`,
  viewRecord: "查看新账单",
  uploadedImage: (v: { index: string | number }) => `已上传图片 ${v.index}`,
  openCamera: "打开相机",
  collapseCamera: "收起相机",
  cameraPreview: "取景画面",
  cameraStarting: "正在启动相机",
  cameraUnavailable: "无法使用相机，请检查相机权限，或关闭其他正在使用相机的应用。",
  cameraUnsupported: "此浏览器不支持直接拍照，请从相册选择照片或直接输入文字。",
  cameraInsecure: "当前地址不是 HTTPS，浏览器不允许打开相机。请改用相册或直接输入文字。",
  capturePhoto: "拍照",
  switchCamera: "切换前后摄像头",
  dropImages: "松开即可添加图片",
};

export const sourceDocumentEditRetryDialogCopy = {
  title: "修改后重新处理",
  loadError: "无法加载原始凭证。",
  reload: "重新加载",
};

export const sourceDocumentDetailCopy = {
  selectCategory: "选择分类",
  select: "选择",
  cancelSelect: "取消",
  noEntries: "暂无明细项目",
  deleteConfirmDesc: "确定要删除这张账单吗？账单里的明细会一起删除，此操作无法撤销。",
  rawContent: "原始输入",
  rawEvidence: "原始凭证",
  entriesTab: "明细",
  evidenceTab: (v: { count: string | number }) => `原始凭证 (${v.count})`,
  processingReadOnly: "账单正在处理，处理完成前不能修改。",
  entryReplaced: "账单已被重新处理，已刷新为最新内容",
  titleLabel: "账单标题",
  deleteDocument: "删除账单",
  noEvidence: "暂无原始凭证",
  transactionTime: "交易时间",
  pendingRecalculation: "正在按新日期重新换算",
  untitled: "未命名账单",
  addEntryTitle: "添加明细",
  addEntryName: "名称",
  addEntryNamePlaceholder: "明细名称",
  addEntryDescription: "备注（可选）",
  addEntryDescriptionPlaceholder: "补充说明",
  addEntryAmount: "金额",
  addEntryCategory: "类别",
  addEntryNoCategory: "未选择",
  addEntryCurrency: "币种",
  addEntrySuccess: "已添加明细",
  addEntryError: "添加明细失败",
  batchUpdateSuccess: (v: { count: string | number }) => `已更新 ${v.count} 条明细`,
  batchUpdateError: "更新失败",
  batchDeleteSuccess: (v: { count: string | number }) => `已删除 ${v.count} 条明细`,
  batchDeleteError: "删除失败",
  batchDeleteTitle: "删除所选明细",
  batchDeleteDescription: (v: { count: string | number }) =>
    `确定删除所选 ${v.count} 项明细吗？此操作无法撤销。`,
  deleteEntryTitle: "删除明细",
  deleteEntryDescription: "确定删除此项明细吗？此操作无法撤销。",
  batchDeletePartial: (v: { count: string | number }) => `${v.count} 项删除失败，已保留选中状态`,
  activeResultTitle: "保留的当前结果",
  activeResultDescription: "以下明细为当前有效结果，重新处理期间仍继续使用。",
  splitTitle: "拆分账单",
  splitDescription: (v: { count: string | number }) =>
    `将选中的 ${v.count} 项明细移动到一张新账单。`,
  splitMore: (v: { count: string | number }) => `另有 ${v.count} 条`,
  splitDate: "新账单日期",
  splitSuccess: (v: { count: string | number }) => `已将 ${v.count} 项明细拆分为新账单`,
  splitFailed: "拆分失败，未保存任何更改",
  splitKeepOne: "原账单至少需要保留一项",
  viewSplitBill: "查看新账单",
  loadError: "账单加载失败。弹窗会保持打开，您可以原位重试。",
  dateOrganization: {
    title: "日期整理建议",
    dismiss: "忽略",
    adjust: "调整",
    applyAll: "全部应用",
    cancel: "取消",
    done: "完成调整",
    applyFailed: "应用失败，账单未更改。请重试。",
    groupDate: "分组日期",
  },
};

export const sourceDocumentImageModalCopy = {
  title: "查看图片",
  titleWithIndex: (v: { current: string | number; total: string | number }) =>
    `图片 ${v.current}/${v.total}`,
  imageAlt: (v: { index: string | number }) => `图片 ${v.index}`,
  close: "关闭",
  previous: "上一张图片",
  next: "下一张图片",
  zoomIn: "放大",
  zoomOut: "缩小",
  resetZoom: "重置缩放",
};

export const sourceDocumentActionCopy = {
  cancelProcessing: "取消处理",
  cancelSuccess: "已取消处理",
  cancelError: "无法取消处理，已刷新为最新结果。",
  retry: "重新处理",
  editRetry: "修改后重新处理",
  retrySuccess: "已开始重新处理",
  retryError: "重新处理失败",
};

export const diagnosticCodeCopy = {
  unparsableDocument: "无法解析",
  unparsableDocumentDesc:
    "AI 未能从这张账单中解析出可记账的支出。可以换一张更清晰的图片，或补充文字说明后重新处理。",
  aiProviderUnavailable: "AI 服务不可用",
  aiProviderUnavailableDesc: "AI 提供方暂时不可用。请稍后重试。",
  aiSchemaInvalid: "AI 响应无效",
  aiSchemaInvalidDesc: "AI 返回了意外的响应格式。此问题已记录，将会被审查。",
  exchangeRateFailure: "汇率错误",
  exchangeRateFailureDesc: "无法获取货币换算的汇率。请稍后重试。",
  storageFailure: "存储错误",
  storageFailureDesc: "保存数据时发生存储错误。请重试。",
  processingUnavailable: "处理不可用",
  processingUnavailableDesc: "解析服务暂时不可用。请稍后重试。",
  requestBoundRetryExhausted: "重试已耗尽",
  requestBoundRetryExhaustedDesc: "所有自动重试尝试已耗尽。请尝试手动修正或重新处理。",
  processingTimeout: "处理超时",
  processingTimeoutDesc: "处理时间过长，任务已停止。请重试。",
};

export const quickEntryFormCopy = {
  selectCategory: "选择分类",
  selectDate: "选择日期",
  currency: "货币",
  selectCurrency: "选择货币",
  amount: "金额",
  itemName: "名称（可选）",
  itemNamePlaceholder: "默认使用分类名称：",
  record: "记一笔",
  quickEntrySuccess: "已记一笔",
  quickEntryError: "记账失败",
  amountRequired: "请输入金额",
  categoryRequired: "请选择分类",
  noCategories: "请先创建分类，再添加快速记录。",
  goToSettings: "前往设置",
};
