export const sourceDocumentCardCopy = {
  expand: "展开",
  collapse: "折叠",
  editRetry: "编辑重试",
  moreActions: "更多操作",
  image: "图片",
  imageAlt: (v: { index: string | number }) => `图片 ${v.index}`,
  untitled: "未命名账单",
  processing: "处理中",
  completed: "已完成",
  cancelled: "已取消",
  dateUnknown: "日期未知",
};

export const sourceDocumentInputCopy = {
  placeholder: "输入消费记录，例如：午饭 35 元… (支持粘贴图片)",
  image: "图片",
  send: "发送",
  uploadSuccess: "提交成功",
  retrySuccess: "重试已提交",
  retryError: "重试失败",
  entryDate: "日期（可选）",
  preparing: "正在准备图片",
  uploading: "正在上传图片",
  finalizing: "正在确认上传",
  submitting: "正在创建记录，此阶段无法取消",
  cancelling: "正在取消上传…",
  imageTooLarge: (v: { fileName: string | number }) =>
    `图片过大：${v.fileName}。请使用更小的图片。`,
  imageUnsupported: (v: { fileName: string | number }) =>
    `不支持的图片格式：${v.fileName}。请使用 JPEG、PNG、GIF 或 WebP。`,
  imageReadError: "无法读取所选图片，请重新选择。",
  imageUploadError: "图片上传失败，输入内容已保留，请重试。",
  networkError: "网络请求已中断，输入内容已保留，请重试。",
  validationError: "记录内容校验失败，请检查后重试。",
  createError: "创建记录失败，输入内容已保留，请重试。",
  tooManyImages: (v: { count: string | number }) => `最多只能上传 ${v.count} 张图片。`,
  cancelUpload: "取消上传",
  savedMayBeHidden: "已保存，但当前筛选可能隐藏这条记录。",
  savedToOtherBook: (v: { book: string | number }) =>
    `已保存到「${v.book}」，当前视图不会显示这条记录。`,
  viewRecord: "查看新记录",
  uploadedImage: (v: { index: string | number }) => `已上传图片 ${v.index}`,
  openCamera: "打开相机",
  collapseCamera: "收起相机",
  cameraPreview: "取景画面",
  cameraStarting: "正在启动相机",
  cameraUnavailable: "无法使用相机，请检查相机权限，或关闭其他正在使用相机的应用。",
  cameraUnsupported: "此浏览器不支持直接拍照，请从相册选择照片或直接输入文字。",
  cameraInsecure: "当前地址不是 HTTPS，浏览器不允许打开相机。请改用相册或直接输入文字。",
  capturePhoto: "拍照",
  switchCamera: "切换前后摄像头",
  dropImages: "松开即可添加图片",
};

export const sourceDocumentEditRetryDialogCopy = {
  title: "编辑重试",
  loadError: "无法加载原始凭证。",
  reload: "重新加载",
  continueEditing: "继续编辑",
};

export const sourceDocumentDetailCopy = {
  title: "账单详情",
  entries: "明细项目",
  selectCategory: "选择分类",
  select: "选择",
  cancelSelect: "取消",
  done: "完成",
  deselectAll: "取消全选",
  noEntries: "暂无明细项目",
  deleteConfirmDesc: "确定要删除此原始凭证吗？这将同时删除所有关联的账本记录。",
  rawContent: "原始输入",
  rawEvidence: "原始凭证",
  noEvidence: "暂无原始凭证",
  viewEvidence: "原始凭证",
  backToDetails: "返回明细",
  transactionTime: "交易时间",
  pendingRecalculation: "保存后将按新日期重新换算",
  editRetry: "编辑重试",
  untitled: "未命名账单",
  saveChanges: (v: { count: string | number }) => `保存 (${v.count}处修改)`,
  cancelEdit: "取消编辑",
  discardChanges: "放弃修改",
  addEntryTitle: "添加明细",
  addEntryName: "名称",
  addEntryNamePlaceholder: "明细名称",
  addEntryAmount: "金额",
  addEntryCategory: "类别",
  addEntryNoCategory: "未选择",
  addEntryCurrency: "币种",
  addEntrySuccess: "已添加明细",
  addEntryError: "添加明细失败",
  unsavedChanges: "有未保存的修改",
  unsavedChangesDesc: "您有未保存的修改，确定要放弃这些修改吗？",
  batchUpdateSuccess: (v: { count: string | number }) => `已更新 ${v.count} 条记录`,
  batchUpdateError: "更新失败",
  batchDeleteSuccess: (v: { count: string | number }) => `已删除 ${v.count} 条记录`,
  batchDeleteError: "删除失败",
  batchDeleteTitle: "删除所选明细",
  batchDeleteDescription: (v: { count: string | number }) =>
    `确定删除所选 ${v.count} 项明细吗？此操作无法撤销。`,
  deleteEntryTitle: "删除明细",
  deleteEntryDescription: "确定删除此项明细吗？此操作无法撤销。",
  batchDeletePartial: (v: { count: string | number }) => `${v.count} 项删除失败，已保留选中状态`,
  saveAllSuccess: (v: { count: string | number }) => `已保存 ${v.count} 处修改`,
  saveAllFailed: "未保存任何更改，请修正问题后重试",
  saveConflict: "未保存，数据已发生变化，请取消编辑后重新修改",
  activeResultTitle: "保留的当前结果",
  activeResultDescription: "以下明细为当前有效结果，重试处理期间仍继续使用。",
  splitTitle: "拆分账单",
  splitDescription: (v: { count: string | number }) =>
    `将选中的 ${v.count} 项明细移动到一张新账单。`,
  splitMore: (v: { count: string | number }) => `另有 ${v.count} 条`,
  splitDate: "新账单日期",
  splitSuccess: (v: { count: string | number }) => `已将 ${v.count} 项明细拆分为新账单`,
  splitFailed: "拆分失败，未保存任何更改",
  splitKeepOne: "原账单至少需要保留一项",
  viewSplitBill: "查看新账单",
  loadError: "账单加载失败。弹窗会保持打开，您可以原位重试。",
  reloadFailed: "重新加载失败，本地修改仍已保留。",
  saveBeforeActionTitle: "先保存当前修改？",
  saveBeforeActionDescription: "先保存当前编辑，再继续所选操作。保存失败时不会执行后续操作。",
  saveAndContinue: "保存并继续",
  batchModePendingTitle: "先处理当前修改",
  batchModePendingDescription: "进入批量操作前，请保存或放弃当前编辑。",
  dateOrganization: {
    title: "日期整理建议",
    dismiss: "忽略",
    adjust: "调整",
    applyAll: "全部应用",
    cancel: "取消",
    done: "完成调整",
    applyFailed: "应用失败，账单未更改。请重试。",
    groupDate: "分组日期",
  },
  book: "分账",
  bookDesc: "把这条记录移到其他分账。",
};

export const sourceDocumentImageModalCopy = {
  title: "查看图片",
  titleWithIndex: (v: { current: string | number; total: string | number }) =>
    `图片 ${v.current}/${v.total}`,
  imageAlt: (v: { index: string | number }) => `图片 ${v.index}`,
  edit: "编辑当前图片",
  close: "关闭",
  previous: "上一张图片",
  next: "下一张图片",
  zoomIn: "放大",
  zoomOut: "缩小",
  resetZoom: "重置缩放",
  continueEditing: "继续编辑",
};

export const sourceDocumentActionCopy = {
  cancelProcessing: "取消处理",
  cancelSuccess: "已取消处理",
  cancelError: "无法取消处理，已刷新为最新结果。",
  retry: "重新处理",
  editRetry: "编辑重试",
  retrySuccess: "已开始重试",
  retryError: "重试失败",
};

export const diagnosticCodeCopy = {
  unparsableDocument: "无法解析",
  unparsableDocumentDesc:
    "AI 未能从这份单据中解析出可记账的支出。可以换一张更清晰的图片，或补充文字说明后重试。",
  aiProviderUnavailable: "AI 服务不可用",
  aiProviderUnavailableDesc: "AI 提供方暂时不可用。请稍后重试。",
  aiSchemaInvalid: "AI 响应无效",
  aiSchemaInvalidDesc: "AI 返回了意外的响应格式。此问题已记录，将会被审查。",
  exchangeRateFailure: "汇率错误",
  exchangeRateFailureDesc: "无法获取货币换算的汇率。请稍后重试。",
  storageFailure: "存储错误",
  storageFailureDesc: "保存数据时发生存储错误。请重试。",
  processingUnavailable: "处理不可用",
  processingUnavailableDesc: "解析服务暂时不可用。请稍后重试。",
  requestBoundRetryExhausted: "重试已耗尽",
  requestBoundRetryExhaustedDesc: "所有自动重试尝试已耗尽。请尝试手动修正或重新处理。",
  processingTimeout: "处理超时",
  processingTimeoutDesc: "处理时间过长，任务已停止。请重试。",
};

export const quickEntryFormCopy = {
  selectCategory: "选择分类",
  selectDate: "选择日期",
  currency: "货币",
  selectCurrency: "选择货币",
  amount: "金额",
  itemName: "名称（可选）",
  itemNamePlaceholder: "默认使用分类名称：",
  record: "记一笔",
  quickEntrySuccess: "记录成功",
  quickEntryError: "记录失败",
  amountRequired: "请输入金额",
  categoryRequired: "请选择分类",
  noCategories: "请先创建分类，再添加快速记录。",
  goToSettings: "前往设置",
  book: "分账",
};
